#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
bundle exec htmlproofer ./_site --check-html --check-sri --url-ignore "https://uk.linkedin.com/in/kkaspate"
gem build jekyll-theme-minimal.gemspec
